# Generated by Django 5.1.4 on 2025-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0003_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
